### PR TITLE
docs: Updated LLM RAG threats diagram

### PR DESCRIPTION
**Pull request by vicenteherrera**
Updated the diagram with several improvements:
* Separated process to feed initial data in the vector database, with general inference
* Relocated threats references taking the separation in consideration

It has been added in the markdown as PNG because it shows more compatibility on rendering (specifically for taking the full width of the document), but the SVG is also included.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Fantastic - thanks @vicenteherrera

**Comment by lucaborella89** [comment]
@vicenteherrera I was told that in the diagram, "Inference Environment SaaS" appears twice; this can be a little confusing

**Comment by vicenteherrera** [comment]
Thanks Luca,

There are two separate phases, to load data into the vector database, and a different one to run inference; the inference env. saas is repeated to make it more clear and not mix lines that would entangle it.

But I get what you say, let me try al alternative representation that keeps the view simple but makes it more clear what I'm saying.

**Comment by vicenteherrera** [comment]
I've create a PR that includes a new version of the diagram here: https://github.com/finos/ai-readiness/pull/58

**Pull request merged**
